export const SEARCH_SAVE_SEARCH_HISTORY = "SEARCH_SAVE_SEARCH_HISTORY" // 保存搜索记录
export const SEARCH_DELETE_ALL_SEARCH_HISTORY = "SEARCH_DELETE_ALL_SEARCH_HISTORY" //清空历史记录
export const COM_SET_SHOWTABBAR_TRUE = "COM_SET_SHOWTABBAR_TRUE" // 设置isShowBottomTabBar为true
export const COM_SET_SHOWTABBAR_FALSE = "COM_SET_SHOWTABBAR_FALSE" // 设置isShowBottomTabBar为false
export const COM_SET_HOME_SWIPER_INDEX = "COM_SET_HOME_SWIPER_INDEX" // 设置swiper的index值